<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Messages - Copy\**" />
    <EmbeddedResource Remove="Messages - Copy\**" />
    <None Remove="Messages - Copy\**" />
  </ItemGroup>

</Project>
