<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransGo.Core\TransGo.Core.csproj" />
    <ProjectReference Include="..\TransGo.Audio.Windows\TransGo.Audio.Windows.csproj" />
  </ItemGroup>

</Project>
