<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransGo.OverlapBenchmark\TransGo.OverlapBenchmark.csproj" />
    <ProjectReference Include="..\TransGo.OverlapTuner\TransGo.OverlapTuner.csproj" />
  </ItemGroup>

</Project>
